// Builds what the browser loads, from sources in this repo and the synced kit:
//   public/app/deck-themes.css  every kit scheme and style, scoped to a slide (.dk-theme) instead of the page
//   public/app/decks.js         the app's screens (src/client), bundled with Yjs by esbuild
//   screens.mjs                 the suite's screen part: the same screens with their styles inside
// --check fails when a built file is out of date.
import fs from 'node:fs';
import { build } from 'esbuild';
import { scopeCss } from './scope-css.mjs';

const check = process.argv.includes('--check');
const out = {};

// 1. Deck themes. The kit sets its options on <html>; a deck sets them on each slide, so the same rules
// are rewritten to apply to any element with class dk-theme, and the colours the kit mixes from the
// seeds are mixed again there.
{
  const tokens = fs.readFileSync('public/ui/src/tokens.css', 'utf8');
  const ui = fs.readFileSync('public/ui/src/ui.css', 'utf8');
  const body = tokens.split('\n').filter((l) => !l.startsWith('@font-face') && !l.startsWith('/*') && !/^\s+(Load after|data-density)/.test(l)).join('\n')
    .replaceAll(':root:where(', '.dk-theme:where(');
  const roots = [...ui.matchAll(/:where\(:root\)\{([^}]*)\}/g)].map((m) => m[1]);
  const derived = roots.slice(1).join(';').replace(/\s+/g, ' ');
  out['public/app/deck-themes.css'] = `/* GENERATED by scripts/build.mjs from the ui-design kit (public/ui/src). Do not edit by hand.
   The kit's schemes and styles, on any element with class dk-theme and data-scheme, data-mode and the rest. */
${body.trim()}
:where(.dk-theme){${derived}}
`;
}

// 2 and 3. The screens.
const bundle = async (entry, extra = {}) => (await build({ entryPoints: [entry], bundle: true, format: 'esm', platform: 'browser', target: 'es2022', minify: true, write: false, legalComments: 'none', ...extra })).outputFiles[0].text;
out['public/app/decks.js'] = `// GENERATED by scripts/build.mjs from src/client. Do not edit by hand. Includes Yjs (MIT).\n${await bundle('src/client/page.mjs')}`;
const css = scopeCss(fs.readFileSync('public/app/decks.css', 'utf8'), '.decks-root') + out['public/app/deck-themes.css'].replace(/^\/\*[\s\S]*?\*\//, '');
out['screens.mjs'] = `// GENERATED by scripts/build.mjs from src/client and public/app/decks.css. Do not edit by hand.\n${await bundle('src/client/screens-entry.mjs', { define: { DECKS_CSS: JSON.stringify(css) } })}`;

let stale = 0;
for (const [f, text] of Object.entries(out)) {
  if (check) {
    if (!fs.existsSync(f) || fs.readFileSync(f, 'utf8') !== text) { console.error(`${f} is out of date: run npm run bundle`); stale++; }
  } else {
    fs.writeFileSync(f, text);
    console.log(`wrote ${f} (${Math.round(text.length / 1024)} KB)`);
  }
}
if (check) { if (stale) process.exit(1); console.log('built files are current'); }
